### ISSUE TITLE
[BUG] IndexOutOfBoundsException in replace

### ISSUE THREAD

**Issue by jgabrielfreitas** [pinball83/Masked-Edittext#16] opened 2016-07-02 05:23 UTC
Hi @pinball83 

I tried resolve this bugs, but I can't.
Can you help me with this cases?

I'm using this mask: `whatever:mask="***.***.***-**"` and `whatever:notMaskedSymbol="*"`.
Using the **SwiftKey keyboard**, when you hold **backspace** button, the EditText loses his mask.
Using the **SwiftKey keyboard** again... when you tap on `,` character, the mask loses one char.

Follow the stacktrace of the first crash(hold backspace button):

```
java.lang.IndexOutOfBoundsException: replace (13 ... 14) ends beyond length 13
at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1264)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:516)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:510)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
at com.github.pinball83.maskededittext.MaskedMaterialEditText$MaskedInputFilter.filter(MaskedMaterialEditText.java:328)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:520)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:510)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
at android.widget.TextView.doKeyDown(TextView.java:6280)
at android.widget.TextView.onKeyDown(TextView.java:6070)
at android.view.KeyEvent.dispatch(KeyEvent.java:2675)
at android.view.View.dispatchKeyEvent(View.java:9876)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:379)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.support.v4.view.ViewPager.dispatchKeyEvent(ViewPager.java:2652)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:402)
at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1787)
at android.app.Activity.dispatchKeyEvent(Activity.java:3020)
at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:316)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4297)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4268)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3819)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3872)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3838)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3965)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3846)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4022)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3819)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3872)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3838)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3846)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3819)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6180)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6154)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6115)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3617)
at android.os.Handler.dispatchMessage(Handler.java:102)
```

**Comment by Nublo** [comment] 2016-07-02 20:08
It is a duplicate of #6 and already fixed in pull request but wasn't merged now.

**Comment by jgabrielfreitas** [comment] 2016-07-03 01:56
Hi @Nublo 
Which pull request?

**Comment by Nublo** [comment] 2016-07-03 14:21
Hi @jgabrielfreitas. 
#13

**Comment by jgabrielfreitas** [comment] 2016-07-04 01:55
Thank you very much @Nublo

**Closed as completed** 2016-07-04 15:08 UTC
